spring:
  messages:
    basename: messages
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  mode: DEVELOPMENT
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/programmentwurf2?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: TRACE
      nodeValue: WARN
    blog: WARN
server:
  port: 8082
